kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd-24-rhel8
  labels:
    app: httpd-24-rhel8
    app.kubernetes.io/component: httpd-24-rhel8
    app.kubernetes.io/instance: httpd-24-rhel8
    app.kubernetes.io/part-of: httpd-24-rhel8-app
    app.openshift.io/runtime-namespace: httpd-test
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: httpd-24-rhel8
  template:
    metadata:
      labels:
        app: httpd-24-rhel8
        deploymentconfig: httpd-24-rhel8
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: httpd-24-rhel8
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository}}:{{ .Values.image.tag}}"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
